language: objective-c
env:
  matrix:
    - TRAVIS_NODE_VERSION="0.10"
    - TRAVIS_NODE_VERSION="0.12"
    - TRAVIS_NODE_VERSION="4.0"
    - TRAVIS_NODE_VERSION="4.1"
    - TRAVIS_NODE_VERSION="5"
sudo: false
before_install:
  - brew install libusb
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - PATH="`npm bin`:`npm bin -g`:$PATH"
  - npm install
  - npm install git://github.com/hybridgroup/cylon.git
  - npm install -g jshint istanbul codeclimate-test-reporter
script:
  - node --version
  - npm --version
  - make ci
  - CODECLIMATE_REPO_TOKEN=476fff97ea6eb7507dcadccd4be385186c37c129b6d9de5ad5104b2714af0c56 codeclimate-test-reporter < coverage/lcov.info
